FROM node:19-slim as build

WORKDIR /app

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

# Use build args to inject the environment variables
ARG REACT_APP_SERVER_URL

# Make sure the environment variables are set during the build stage
ENV REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]