FROM node:19

WORKDIR /app

COPY ./package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

# Convert typescript to javascript
RUN npm run build

EXPOSE 8080

CMD ["node", "dist/server.js"]