service: demoDataService

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

useDotenv: true

functions:
  populateData:
    handler: demoData.handler
    events:
      - schedule:
          rate: rate(3 days)
    environment:
      DB_CONNECTION_STRING: ${env:DB_CONNECTION_STRING}

plugins:
  - serverless-dotenv-plugin